version: '3.4'

services:
  web:
    build: .
    environment:
      - ASPNETCORE_URLS=http://+:80  # This line sets the listen URL for the web service
    depends_on:
      - db
    ports:
      - "8080:80"  # This line maps port 8080 on the host to port 80 on the container

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password1.
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  proxy:
    image: caddy
    ports:
      - "80:80"  # Public HTTP port
      - "443:443"  # Public HTTPS port
    volumes:
      - ./data/data:/data
      - ./data/config:/config
      - ./data/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - web

volumes:
  postgres_data: